name: Run CI in Docker

on: [pull_request, workflow_call]

jobs:
  ci-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build django-app on Docker
        run: docker build . -t django-app --target production

      - name: Run endpoint check
        run: |
          docker run --rm -d --name django-app-container -p 80:80 django-app
          sleep 5
          curl --fail http://0.0.0.0:80
